In [6]:
import zipfile
with zipfile.ZipFile('HUPA-UC Diabetes Dataset.zip', 'r') as zip_ref:
    zip_ref.extractall('documents/GitHub/team9_PyCoders_PythonHackathon_MAY2026')

In [7]:
import pandas as pd
import glob
import os

In [8]:
path = "HUPA-UC Diabetes Dataset/*.csv"
import glob

files = glob.glob(path)
print(files[:5])

['HUPA-UC Diabetes Dataset/HUPA0023P.csv', 'HUPA-UC Diabetes Dataset/HUPA0019P.csv', 'HUPA-UC Diabetes Dataset/HUPA0015P.csv', 'HUPA-UC Diabetes Dataset/T1DM_patient_sleep_demographics_with_race.csv', 'HUPA-UC Diabetes Dataset/HUPA0003P.csv']

In [9]:
patient_files = [f for f in files if os.path.basename(f).startswith("HUPA")] # just taking files starting with HUPA
print("Patient monitoring files:", len(patient_files))

Patient monitoring files: 25

In [10]:
all_data = []

for file in patient_files:
    df = pd.read_csv(file, sep=';')
    
    patient_id = os.path.basename(file).replace(".csv","")
    df["Patient_ID"] = patient_id
    
    all_data.append(df)

master_df = pd.concat(all_data, ignore_index=True)

In [11]:

master_df.head()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,Patient_ID
0,2020-01-17T00:00:00,40.000000,15.0429,96.371901,8.0,0.035,0.0,1.0,HUPA0023P
1,2020-01-17T00:05:00,41.333333,8.3164,91.395349,0.0,0.035,0.0,0.0,HUPA0023P
2,2020-01-17T00:10:00,42.666667,7.5826,85.991935,0.0,0.035,0.0,0.0,HUPA0023P
3,2020-01-17T00:15:00,44.000000,7.3380,82.434426,0.0,0.035,0.0,0.0,HUPA0023P
4,2020-01-17T00:20:00,50.000000,7.5826,78.822581,0.0,0.035,0.0,0.0,HUPA0023P

In [12]:
print(master_df.columns)

Index(['time', 'glucose', 'calories', 'heart_rate', 'steps', 'basal_rate',
       'bolus_volume_delivered', 'carb_input', 'Patient_ID'],
      dtype='object')

In [13]:
meta = pd.read_csv("HUPA-UC Diabetes Dataset/T1DM_patient_sleep_demographics_with_race.csv") # reading sleep demographics.csv 
print(meta.head())
print(meta.columns)

  Patient_ID  Age  Gender             Race  Average Sleep Duration (hrs)  \
0  HUPA0001P   34    Male            Other                           6.3
1  HUPA0002P   49    Male         Hispanic                           6.6
2  HUPA0003P   64    Male            Black                           5.3
3  HUPA0004P   34  Female  Native American                           5.2
4  HUPA0005P   49    Male  Native American                           5.8

   Sleep Quality (1-10)  % with Sleep Disturbances
0                   4.5                         80
1                   4.4                         40
2                   5.2                         70
3                   6.9                         60
4                   7.9                         30
Index(['Patient_ID', 'Age', 'Gender', 'Race', 'Average Sleep Duration (hrs)',
       'Sleep Quality (1-10)', '% with Sleep Disturbances'],
      dtype='object')

In [14]:
master_df = master_df.merge(meta, on="Patient_ID", how="left") # merging sleep demographics with the mater data frame

In [15]:
master_df.head()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,Patient_ID,Age,Gender,Race,Average Sleep Duration (hrs),Sleep Quality (1-10),% with Sleep Disturbances
0,2020-01-17T00:00:00,40.000000,15.0429,96.371901,8.0,0.035,0.0,1.0,HUPA0023P,74,Female,Black,5.1,6.8,40
1,2020-01-17T00:05:00,41.333333,8.3164,91.395349,0.0,0.035,0.0,0.0,HUPA0023P,74,Female,Black,5.1,6.8,40
2,2020-01-17T00:10:00,42.666667,7.5826,85.991935,0.0,0.035,0.0,0.0,HUPA0023P,74,Female,Black,5.1,6.8,40
3,2020-01-17T00:15:00,44.000000,7.3380,82.434426,0.0,0.035,0.0,0.0,HUPA0023P,74,Female,Black,5.1,6.8,40
4,2020-01-17T00:20:00,50.000000,7.5826,78.822581,0.0,0.035,0.0,0.0,HUPA0023P,74,Female,Black,5.1,6.8,40

In [16]:
%store master_df

Stored 'master_df' (DataFrame)